export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER"; // who the user is that is logged in
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_INIT = "FETCH_BOOKS_INIT";
export const FETCH_BOOKS_FAIL = "FETCH_BOOKS_FAIL";

export const FETCH_BOOK_BY_ID_SUCCESS = "FETCH_BOOK_BY_ID_SUCCESS";
export const FETCH_BOOK_BY_ID_INIT = "FETCH_BOOK_BY_ID_INIT";

export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_FAIL = "UPDATE_BOOK_FAIL";
export const RESET_BOOK_ERRORS = "RESET_BOOK_ERRORS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
